version: '3.7'
services:
  angular-app:
    container_name: angular_app
    image: angular_app:1.0.0
    build: ./labsmart_frontend
    ports:
      - 4200:4200
    depends_on:
      - java-app
    networks:
      - springboot-mysql-angular-network
  java-app:
    image: labsmart-java-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - jwtKey=${JWT_SECRET}
    networks:
      - springboot-mysql-angular-network
  mysqldb:
    image: mysql:8.3.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./db/data.sql:/docker-entrypoint-initdb.d/data.sql
      - ./db/labsmart.sql:/docker-entrypoint-initdb.d/labsmart.sql
    networks:
      - springboot-mysql-angular-network
volumes:
  mysql-data:
networks:
  springboot-mysql-angular-network:
    name: springboot-mysql-angular-network
